# Generated by Django 4.2.5 on 2023-09-13 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPipelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospectName', models.CharField(max_length=255)),
                ('intermediaryName', models.CharField(max_length=255)),
                ('premiumAmount', models.FloatField()),
                ('businessClass', models.CharField(max_length=50)),
                ('transactionDate', models.DateTimeField(default=datetime.date(2023, 9, 13))),
                ('closureDate', models.DateField()),
                ('currentInsurer', models.CharField(max_length=255)),
                ('likelyHood', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
